---
- name: Clean and Install Apache on Linux VM
  hosts: all
  become: yes
  tasks:
    - name: Remove existing Apache packages
      apt:
        name: apache2
        state: absent
        purge: yes

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache package
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copy custom Apache configuration file (optional)
      # Ensure the source file exists in the local directory or specify the correct path
      copy:
        src: apache2.conf
        dest: /etc/apache2/apache2.conf
        owner: root
        group: root
        mode: '0644'
      # Ensure this task is skipped if you don't have a custom file
      when: false

    - name: Ensure Apache is listening on port 80 (optional)
      # Uncomment if you need to ensure the Apache configuration listens on port 80
      lineinfile:
        path: /etc/apache2/ports.conf
        line: 'Listen 80'
        create: yes
        state: present

    - name: Reload Apache to apply configuration changes
      service:
        name: apache2
        state: reloaded
