---
- hosts: all
  become: true
  tasks:

    # Update the system
    - name: Update apt repository
      apt:
        update_cache: yes

    # Clean up existing Apache installation
    - name: Remove Apache if installed
      apt:
        name: apache2
        state: absent

    # Install Apache
    - name: Install Apache
      apt:
        name: apache2
        state: present
    
    # Modify Apache config to prioritize PHP files
    - name: Modify Apache config to prioritize PHP files
      lineinfile:
        path: /etc/apache2/mods-enabled/dir.conf
        regexp: '^(\s*)DirectoryIndex'
        line: 'DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm'
        state: present
        backrefs: yes

    # Restart Apache to apply changes
    - name: Restart Apache
      systemd:
        name: apache2
        state: restarted

    # Create a test PHP file to confirm PHP installation
    - name: Create PHP info file with additional content
      copy:
        dest: /var/www/html/info.php
        content: |
          <?php
          // Display server info
          echo "<h1>PHP is working!</h1>";
          
          // Display current date and time
          $current_time = date('Y-m-d H:i:s');
          echo "<p>Current server time is: $current_time</p>";

          // Use phpinfo to display PHP configuration
