---
- name: Clean and Install Apache on Linux VM
  hosts: all
  become: yes
  tasks:
    - name: Remove existing Apache packages
      apt:
        name: apache2
        state: absent
        purge: yes

    - name: Remove any residual Apache configuration files
      file:
        path: /etc/apache2
        state: absent
        recurse: yes
        force: yes

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache package
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copy custom Apache configuration file (optional)
      # Uncomment if you have a custom configuration file to deploy
      # copy:
      #   src: /path/to/your/apache2.conf
      #   dest: /etc/apache2/apache2.conf
      #   owner: root
      #   group: root
      #   mode: '0644'

    - name: Ensure Apache is listening on port 80 (optional)
      # Uncomment if you need to ensure the Apache configuration listens on port 80
      lineinfile:
        path: /etc/apache2/ports.conf
        line: 'Listen 80'
        create: yes
        state: present

    - name: Reload Apache to apply configuration changes
      service:
        name: apache2
        state: reloaded
