---
- name: Clean up and reinstall Apache and MySQL
  hosts: all
  become: yes

  tasks:
    # Apache Cleanup and Installation
    - name: Stop Apache service if running
      ansible.builtin.systemd:
        name: apache2
        state: stopped
        enabled: no

    - name: Remove Apache packages
      ansible.builtin.apt:
        name: apache2
        state: absent

    - name: Remove Apache configuration files
      ansible.builtin.file:
        path: /etc/apache2
        state: absent
        recurse: yes
      ignore_errors: yes

    - name: Remove Apache log files
      ansible.builtin.file:
        path: /var/log/apache2
        state: absent
        recurse: yes
      ignore_errors: yes

    - name: Remove Apache cache files
      ansible.builtin.file:
        path: /var/cache/apache2
        state: absent
        recurse: yes
      ignore_errors: yes

    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure actions module is enabled
      ansible.builtin.command:
        cmd: a2enmod actions
        creates: /etc/apache2/mods-enabled/actions.load

    - name: Restart Apache to apply changes
      ansible.builtin.systemd:
        name: apache2
        state: restarted

    # MySQL Cleanup and Installation
    - name: Stop MySQL service if running
      ansible.builtin.systemd:
        name: mysql
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Remove MySQL server package
      ansible.builtin.apt:
        name: mysql-server
        state: absent

    - name: Remove MySQL configuration files
      ansible.builtin.file:
        path: /etc/mysql
        state: absent
        recurse: yes
      ignore_errors: yes

    - name: Remove MySQL log files
      ansible.builtin.file:
        path: /var/log/mysql
        state: absent
        recurse: yes
      ignore_errors: yes

    - name: Install MySQL server
      ansible.builtin.apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Start and enable MySQL service
      ansible.builtin.systemd:
        name: mysql
        state: started
        enabled: yes
