name: Deploy MySQL

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Test SSH Connection
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@213.165.92.7 'echo "SSH connection successful"'

    - name: Run Ansible Playbook
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ansible-playbook -i onlinebusinessmarketplace/ansible/mysql/inventory onlinebusinessmarketplace/ansible/mysql/mysql_install.yaml -vvv
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'False'
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        MYSQL_DB_NAME: ${{ secrets.MYSQL_DB_NAME }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_USER_PASSWORD: ${{ secrets.MYSQL_USER_PASSWORD }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

    - name: Verify MySQL Service
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@213.165.92.7 'systemctl status mysql'
